//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkData.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class SolutionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SolutionSettings defaultInstance = ((SolutionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SolutionSettings())));
        
        public static SolutionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\ImagesAndVideos")]
        public string RootOfMediaFolder {
            get {
                return ((string)(this["RootOfMediaFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MediaTools\\ffmpeg.exe")]
        public string FFmpegPath {
            get {
                return ((string)(this["FFmpegPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MediaTools\\ffprobe.exe")]
        public string FFprobePath {
            get {
                return ((string)(this["FFprobePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\Temp\\Thumbnails")]
        public string ThumbnailsFolder {
            get {
                return ((string)(this["ThumbnailsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.103:9090/")]
        public string BaseApiAddress {
            get {
                return ((string)(this["BaseApiAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"astmus@live.com\":506545376,\"olgas88@live.com\":355747145}")]
        public string TelegramSubscribers {
            get {
                return ((string)(this["TelegramSubscribers"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("688413717:AAELvIkuj37vBedxvzIgtWsjZio8_B4QlR0")]
        public string TelegramSecretKey {
            get {
                return ((string)(this["TelegramSecretKey"]));
            }
            set {
                this["TelegramSecretKey"] = value;
            }
        }
    }
}
